name: Akka.io Doc Site Algolia indexing

on:
  # once it works
  #schedule:
  #  - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: 'read'

jobs:
  scrape_index:
    name: Update search index
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: darrenjennings/algolia-docsearch-action@75b0f6d
        with:
          algolia_application_id: '${{ secrets.ALGOLIA_APPLICATION_ID }}'
          algolia_api_key: '${{ secrets.ALGOLIA_API_KEY }}'
          file: '.algolia-search-index-config.json'